#### general settings
name: chex10000-sde-test
use_tb_logger: true
model: denoising
distortion: deblur
gpu_ids: [0]

sde:
  max_sigma: 10
  T: 100
  schedule: cosine # linear, cosine
  eps: 0.005

degradation: # for some synthetic dataset that only have GTs
  # for denoising
  sigma: 25
  noise_type: G # Gaussian noise: G

  # for super-resolution
  scale: 4
  
#### datasets
datasets:
  number_of_samples: 2
  dataset: chex
  csv_path_LQ: /lotterlab/project_data/CheXpert_noise/metadata_photon_100000.csv
  csv_path_GT: /lotterlab/users/matteo/data/CheXpert/metadata.csv
  dataroot_LQ: /lotterlab/project_data/CheXpert_noise
  dataroot_GT: /lotterlab/datasets/

  use_shuffle: true
  n_workers: 1  
  batch_size: 2
  GT_size: 256
  LR_size: 256
  use_flip: true
  use_rot: true
  color: RGB
#### network structures
network_G:
  which_model_G: ConditionalUNet
  setting:
    in_nc: 1
    out_nc: 1
    nf: 64
    depth: 4

#### path
path:
  pretrain_model_G: ~
  strict_load: true
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  optimizer: Adam # Adam, AdamW, Lion
  lr_G: !!float 1e-4
  lr_scheme: MultiStepLR
  beta1: 0.9
  beta2: 0.99
  #niter: 700000
  niter: 100
  warmup_iter: -1  # no warm up
  lr_steps: [200000, 400000, 600000]
  lr_gamma: 0.5
  eta_min: !!float 1e-7
  # criterion
  is_weighted: False
  loss_type: l1
  weight: 1.0

  manual_seed: 0
#### logger
logger:
  print_per_epoch: 2
  save_checkpoint_freq: 1
