#### general settings
name: ucsf8-sde
use_tb_logger: true
model: denoising
distortion: deblur
gpu_ids: [0]

sde:
  max_sigma: 10
  T: 100
  schedule: cosine # linear, cosine
  eps: 0.005

degradation: # for some synthetic dataset that only have GTs
  # for denoising
  sigma: 25
  noise_type: G # Gaussian noise: G

  # for super-resolution
  scale: 4
  
#### datasets
datasets:
  number_of_samples: 100
  dataset: ucsf
  dataroot: /home/ziwlu/datasets/ucsf/train.csv
  sampling_mask: radial
  type: FLAIR
  pathology: [TODO]
  lower_slice: 60
  upper_slice: 130
  number_of_rays
  number_of_slices: 10

  use_shuffle: true
  n_workers: 8  # per GPU
  batch_size: 4
  GT_size: 256
  LR_size: 256
  use_flip: true
  use_rot: true
  color: RGB
#### network structures
network_G:
  which_model_G: ConditionalUNet
  setting:
    in_nc: 1
    out_nc: 1
    nf: 64
    depth: 4

#### path
path:
  pretrain_model_G: ~
  strict_load: true
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  optimizer: Adam # Adam, AdamW, Lion
  lr_G: !!float 1e-4
  lr_scheme: MultiStepLR
  beta1: 0.9
  beta2: 0.99
  niter: 700000
  warmup_iter: -1  # no warm up
  lr_steps: [200000, 400000, 600000]
  lr_gamma: 0.5
  eta_min: !!float 1e-7

  # criterion
  is_weighted: False
  loss_type: l1
  weight: 1.0

  manual_seed: 0
  val_freq: !!float 5e3

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
