#### general settings
name: chex10000-sde-reweight
use_tb_logger: true
model: denoising
distortion: deblur
gpu_ids: [0]

sde:
  max_sigma: 10
  T: 100
  schedule: cosine # linear, cosine
  eps: 0.005

degradation: # for some synthetic dataset that only have GTs
  # for denoising
  sigma: 25
  noise_type: G # Gaussian noise: G

  # for super-resolution
  scale: 4
  
#### datasets
datasets:
  dataset: chex
  csv_path_LQ: /vol/miltank/projects/practical_SoSe24/mri_inr/matteo/data/CheXpert_noisy/chex-metadata_photon_10000.csv
  csv_path_GT: /vol/miltank/projects/practical_SoSe24/mri_inr/matteo/data/CheXpert/chexpert-metadata-processed.csv
  dataroot_LQ: /vol/miltank/projects/practical_SoSe24/mri_inr/matteo/data/CheXpert_noisy
  dataroot_GT: /vol/miltank/datasets/CheXpert 

  use_shuffle: true
  n_workers: 2 
  batch_size: 8
  GT_size: 256
  LR_size: 256
  use_flip: true
  use_rot: true
  color: RGB
#### network structures
network_G:
  which_model_G: ConditionalUNet
  setting:
    in_nc: 1
    out_nc: 1
    nf: 64
    depth: 4

#### path
path:
  pretrain_model_G: ~
  strict_load: true
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  optimizer: Adam # Adam, AdamW, Lion
  lr_G: !!float 1e-4
  lr_scheme: MultiStepLR
  beta1: 0.9
  beta2: 0.99
  niter: 150000
  warmup_iter: -1  # no warm up
  lr_steps: [200000, 400000, 600000]
  lr_gamma: 0.5
  eta_min: !!float 1e-7
  # criterion
  is_weighted: False
  loss_type: l1
  weight: 1.0

  manual_seed: 0
#### logger
logger:
  print_per_epoch: 2
  save_checkpoint_freq: 10

path:
  pretrain_model_G: /vol/miltank/projects/practical_SoSe24/mri_inr/matteo/code/image-restoration-sde/experiments/deblurring/chex10000-sde/models/40_G.pth
  strict_load: True

fairness_lambda: 0

classifier_path: /vol/miltank/projects/practical_SoSe24/mri_inr/matteo/code/torchxrayvision/chex-densenet-class_norm01-best.pt